### PR TITLE
TestDefinitions with 1:n UnitTestResults

### LINKED ISSUE #37: TestDefinitions with multiple UnitTestResults not recognized correclty
### Summary

When the TRX `TestDefinitions` output does not match the number of `TestEntries` and `Results`.

The JUnit file is a bit dodgy.

Read more here https://github.com/Microsoft/vstest/issues/1989

https://circleci.com/gh/cheng93/TripleTriad/29#tests/containers/0
Is an example 

### Steps to reproduce

* Follow the steps in associated issue
* Create junit file from trx

### What is the current *bug* behavior?

* Counts are wrong in junit

### What is the expected *correct* behavior?

* Counts are correct in junit

### Further technical details
trx2junit-version: v1.2.2
Operating system: linux

----

I will try to get
* Unit test
* trx
* junit xml
when I get home/time

### PR DESCRIPTION
**Pull request by cheng93**
Closes #37 

According to the issue, a `TestDefinition` can have a one to many `UnitTestResults`.

These are identified by `TestId` and `ExecutionId` respectively.

### CODE REVIEW

File: source/trx2junit/Models/Test.cs [hunk 1]
```diff
@@ -5,9 +5,9 @@ namespace trx2junit.Models
...
     public class Test
     {
-        public Times                            Times           { get; set; }
-        public ResultSummary                    ResultSummary   { get; set; }
-        public Dictionary<Guid, TestDefinition> TestDefinitions { get; set; } = new Dictionary<Guid, TestDefinition>();
-        public Dictionary<Guid, UnitTestResult> UnitTestResults { get; set; } = new Dictionary<Guid, UnitTestResult>();
+        public Times                                         Times { get; set; }
+        public ResultSummary                                 ResultSummary { get; set; }
+        public Dictionary<Guid, TestDefinition>              TestDefinitions { get; set; } = new Dictionary<Guid, TestDefinition>();
+        public Dictionary<Guid, ICollection<UnitTestResult>> UnitTestResults { get; set; } = new Dictionary<Guid, ICollection<UnitTestResult>>();
```
Comment (cheng93) [inline source/trx2junit/Models/Test.cs]: Let me sleep on this.

Not sure if I should change this class

Comment (cheng93) [reply source/trx2junit/Models/Test.cs]: Reason I changed this, is so we can look up the `UnitTestResults` for a given `TestId` Key.

However it feels wrong doing it in this class.

I think I may be better to create an `ILookup` or something in the `JUnitBuilder`

**Comment by gfoidl** [comment]
Can you also add a sample for a data-driven test to https://github.com/gfoidl/trx2junit/tree/master/samples/MsTestSample (similar to `SimpleTests.cs`)? 

So far this is for MsTest. I assume that this will also be the case for NUnit (TestCases) and xUnit (Theories). If so, there would be samples and Test-trx in https://github.com/gfoidl/trx2junit/tree/master/tests/trx2junit.Tests/data good to.

If you won't address this, I'll do it in a follow-up.

**Comment by cheng93** [comment]
My data was actually generated using xunit (via dotnet test)

Yea sure, I'll take a look, will have to do it after work

File: tests/trx2junit.Tests/Internal/JUnitBuilderTests/Gh37.cs [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+using System.Collections.Generic;
+using System.Linq;
+using System.Xml.Linq;
+using NUnit.Framework;
+
+namespace trx2junit.Tests.Internal.JUnitBuilderTests
+{
+
+    [TestFixture]
+    public class Gh37
```
Comment (gfoidl) [inline tests/trx2junit.Tests/Internal/JUnitBuilderTests/Gh37.cs]: For this see https://github.com/cheng93/trx2junit/pull/1
After accepting this PR in your clone, it should flow back to this PR here.

File: source/trx2junit/Models/Test.cs (hunk 1 above)
Comment (gfoidl) [reply source/trx2junit/Models/Test.cs]: > I think I may be better to create an `ILookup` or something in the `JUnitBuilder`

Agreed. This logic should be outside of `Test`-class.

File: source/trx2junit/Internal/JUnitBuilder.cs [hunk 3]
```diff
@@ -59,36 +59,38 @@ private void AddTestSuite(string testSuiteName, IEnumerable<KeyValuePair<Guid, T
         //---------------------------------------------------------------------
         private void AddTest(XElement xTestSuite, KeyValuePair<Guid, TestDefinition> test)
         {
-            _testCount++;
+            var unitTestResults = _test.UnitTestResults[test.Key];
```
Comment (gfoidl) [inline source/trx2junit/Internal/JUnitBuilder.cs]:
```suggestion
            ICollection<UnitTestResult> unitTestResults = _test.UnitTestResults[test.Key];
```

But this will be changed either way.

File: source/trx2junit/Models/Test.cs (hunk 1 above)
Comment (gfoidl) [reply source/trx2junit/Models/Test.cs]: Maybe we could model this `1:n` relationship in `TestDefinition` like
```c#
using System;
using System.Collections.Generic;

namespace trx2junit
{
    public class TestDefinition
    {
        public Guid   Id          { get; set; }
        public Guid   ExecutionId { get; set; }
        public string TestClass   { get; set; }
        public string TestMethod  { get; set; }

        public ICollection<UnitTestResult> TestResults { get; set; } = new HashSet<UnitTestResult>();
    }
}
```

And let the `TrxParser` do the work.

What do you think?

**Review by gfoidl — CHANGES_REQUESTED** [review]

File: source/trx2junit/Models/Test.cs (hunk 1 above)
Comment (cheng93) [reply source/trx2junit/Models/Test.cs]: Not sure we need this.

Up to you if you want it modelled this way.

I have a solution which I'm happier with now.

Comment (gfoidl) [reply source/trx2junit/Models/Test.cs]: Your solution looks pretty good and simple 👍 We'll keep it this way.

File: source/trx2junit/Internal/JUnitBuilder.cs [hunk 4]
```diff
@@ -59,36 +63,38 @@ private void AddTestSuite(string testSuiteName, IEnumerable<KeyValuePair<Guid, T
         //---------------------------------------------------------------------
         private void AddTest(XElement xTestSuite, KeyValuePair<Guid, TestDefinition> test)
         {
-            _testCount++;
+            var unitTestResults = _lookup[test.Key];
```
Comment (gfoidl) [inline source/trx2junit/Internal/JUnitBuilder.cs]:
```suggestion
            IEnumerable<UnitTestResult> unitTestResults = _lookup[test.Key];
```

**Review by gfoidl — COMMENTED** [review]
With your change the dictionaries in https://github.com/gfoidl/trx2junit/blob/49ba5dc6fe81a11cb642f39c4f915016be6d1255/source/trx2junit/Models/Test.cs#L6-L12 could go away, as they aren't needed anymore. So `Test` could be
```c#
public class Test
{
    public Times                       Times           { get; set; }
    public ResultSummary               ResultSummary   { get; set; }
    public ICollection<TestDefinition> TestDefinitions { get; set; } = new List<TestDefinition>();
    public ICollection<UnitTestResult> UnitTestResults { get; set; } = new List<UnitTestResult>();
}
```

Can you change this please?

**Review by gfoidl — APPROVED** [review]

**Comment by gfoidl** [comment]
Is anything left from your side?

**Comment by cheng93** [comment]
I can add the data driven test later if you wish.

Will either be later tonight or sometime tomorrow

**Comment by gfoidl** [comment]
I think it's OK to merge this now. This change is good.
Thank you very much!

I'll add some tests (time to play with the other test-frameworks).

**Comment by cheng93** [comment]
Let me know if you need the xunit data generated.
